highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://bvnagababu.github.io/battina
author: BATTINA

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /battina/
title: Battina's Resume
name: BV Nagababu
email: nagababu.battina@gmail.com
email_full: mailto:nagababu.battina@gmail.com
#website: www.trd9.com
#website_full: https://www.trd9.com
github: BVNAGABABU
twitter: BVNaagabaabu
instagram: venkata.naaga
tel: +91 0000 000000
tel_full: tel:+910000000000
google_maps: 'https://www.google.com/maps/place/Teachers+Colony,+HSR+Layout+5th+Sector,+Bengaluru,+Karnataka+560034'
address:
  street: Teachers Colony
  postcode: 560034
  city: Bengalore
  country: India
google_analytics: UA-175062408-1

# needed for travis-ci build
exclude: [vendor]
